TEMPLATES = {
    "classic": {
        "font_name": "Calibri",
        "font_size_name": 22,
        "font_size_title": 12,
        "font_size_contact": 10,
        "font_size_section_heading": 11,
        "font_size_body": 10.5,
        "color_name": "1A1A1A",
        "color_title": "444444",
        "color_contact": "555555",
        "color_section_heading": "1A1A1A",
        "color_rule": "1A1A1A",
        "color_body": "1A1A1A",
        "space_before_section": 14,
        "space_after_heading": 3,
    },
    "modern": {
        "font_name": "Calibri",
        "font_size_name": 22,
        "font_size_title": 12,
        "font_size_contact": 10,
        "font_size_section_heading": 11,
        "font_size_body": 10.5,
        "color_name": "1B3A5C",
        "color_title": "2E86C1",
        "color_contact": "444444",
        "color_section_heading": "1B3A5C",
        "color_rule": "2E86C1",
        "color_body": "1A1A1A",
        "space_before_section": 14,
        "space_after_heading": 3,
    },
    "compact": {
        "font_name": "Calibri",
        "font_size_name": 18,
        "font_size_title": 11,
        "font_size_contact": 9.5,
        "font_size_section_heading": 10,
        "font_size_body": 9.5,
        "color_name": "1A1A1A",
        "color_title": "555555",
        "color_contact": "555555",
        "color_section_heading": "1A1A1A",
        "color_rule": "1A1A1A",
        "color_body": "1A1A1A",
        "space_before_section": 8,
        "space_after_heading": 2,
    },
}

DEFAULT_TEMPLATE = "classic"
